### ISSUE TITLE
https://api.geetest.com/get.php 接口报error_32

### ISSUE THREAD

**Issue by Wayne0902** [GeeTeam/gt-wxminiapp-demo#2]
https://api.geetest.com/get.php看了下这个接口传了challenge，gt，lang，pt，w五个参数，然后报了下面的错，是我组件少传什么prop了吗
![image](https://user-images.githubusercontent.com/12484369/55719298-78047980-5a30-11e9-9c3c-0e753519a29d.png)

**Comment by Wayne0902** [comment]
gt传的其实就是captcha_id...传成别的参数了...

**Comment by ikbs** [comment]
在在在，我想问一下w参数怎么取，可以告知一下吗？918897059 qq谢谢
